---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ajay.dev
  resources:
  - configspecs/finalizers
  verbs:
  - update
- apiGroups:
  - ajay.dev
  resources:
  - configspecs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ajay.dev
  - config.ajay.dev
  resources:
  - configspecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
